### ISSUE TITLE
import LoggerAPI is required too

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/HeliumLogger#12]
The usage example:

```swift
import HeliumLogger
Log.logger = HeliumLogger()
Log.verbose("This is a log message.")
```

doesn't actually compile.

```swift
import LoggerAPI
```

is required too.  Can we remove the requirement to import LoggerAPI?

**Comment by shmuelk** [comment]
If all you want to do in your main.swift is set up HeliumLogger then all you need to do is:

```swift
import HeliumLogger

HeliumLogger.use()
```

If you want to actually log using the Logger, then you need to import LoggerAPI. We have until now avoided adding the unsupported tag @_exported, which causes everything a module has imported to be exported. Supposedly there are issues with XCode with using that tag.

**Comment by ianpartridge** [comment]
Thanks Shmuel, in that case I will update the README to add `import LoggerAPI` too.

**Comment by ianpartridge** [comment]
@dfirsht I'd already made this change, on `develop`?

**Comment by dfirsht** [comment]
yeah it just got merged to master, i guess the merge re-closes it.

**Comment by ianpartridge** [comment]
Oh cool, didn't know about that feature. Thanks.
