### ISSUE TITLE
Setup CI for HeliumLogger

### ISSUE THREAD

**Issue by kweinmeister** [IBM-Swift/HeliumLogger#3]

**Comment by rfdickerson** [comment]
Good news, I have discovered a way to build Swift-DEVELOPMENT-04-12 apps in Travis without needing to start a docker container. Running in XCode 7.3 + Mac OS environment and then pulling down the toolchain from swift.org and building then testing.

@dfirsht There is a little problem I'm having with explicit first argument stuff. Might need your help here.

https://travis-ci.org/IBM-Swift/HeliumLogger/builds/123446404

**Comment by dfirsht** [comment]
HeliumLogger has had working CI for quite some time now.
