### ISSUE TITLE
The dependency graph could not be satisfied (https://github.com/IBM-Swift/HeliumLogger.git)

### ISSUE THREAD

**Issue by penacristian** [IBM-Swift/HeliumLogger#39]
I'm getting that error when trying to do
`swift package generate-xcodeproj`
The xcode project is not updating after adding a coachDB package dependency.
Any idea??

**Comment by ianpartridge** [comment]
Can you paste your full `Package.swift` here please?

**Comment by penacristian** [comment]
`import PackageDescription

let package = Package(
    name: "Kitura-Starter",
    targets: [
      Target(name: "Kitura-Starter", dependencies: [])
    ],
    dependencies: [
      .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 3),
      .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1, minor: 3),
      .Package(url: "https://github.com/IBM-Swift/Swift-cfenv.git", majorVersion: 1, minor: 8),
      .Package(url: "https://github.com/IBM-Swift/SwiftyJSON.git", majorVersion: 15),
      .Package(url: "https://github.com/IBM-Bluemix/cf-deployment-tracker-client-swift.git", majorVersion: 0, minor: 6),
      .Package(url: "https://github.com/IBM-Swift/Kitura-CouchDB.git", majorVersion: 0, minor: 25)
    ],
    exclude: ["Makefile", "Package-Builder"])
`

**Comment by ianpartridge** [comment]
Thanks. You've specified version 0.25 of `Kitura-CouchDB` which is a very old version that used a different `HeliumLogger`.

Change your `Package.swift` to specify version 1.3 of `Kitura-CouchDB`, then `rm -rf Packages` and run `swift package generate-xcodeproj` again.

**Comment by penacristian** [comment]
How can I specify a minimum version and just get the latest? (kind of like cocoapods)

**Comment by ianpartridge** [comment]
Swift Package Manager doesn't support that model, I'm afraid.

**Comment by penacristian** [comment]
And how should I get notified which is the latest version? Or where can I check?

**Comment by penacristian** [comment]
Also, do you know of any good documentation/tutorial on using CouchDB with Kitura?

**Comment by ianpartridge** [comment]
Swift Package Manager versioning is based on git tags and [SemVer](http://www.semver.org). So, for `Kitura-CouchDB` you can check the [releases page](https://github.com/IBM-Swift/Kitura-CouchDB/releases) to see the most recent version.

**Comment by penacristian** [comment]
Thank you very much for everything

**Comment by ianpartridge** [comment]
There's a tutorial [here](https://akrabat.com/kitura-tutorial-2/) written by @akrabat.
