### ISSUE TITLE
Error when building on Ubuntu 16.10 with Swift 3.0.2

### ISSUE THREAD

**Issue by joem2600** [IBM-Swift/HeliumLogger#43]
Hi, 
 I tried to compile a simple hello world program using HeliumLogger and the swift compiler failed to compile due to an error with HeliumLogger. 

Cheers,
Joe

.Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1, minor: 6)

 Here is the output:

Compile Swift Module 'SSLService' (1 sources)
Compile Swift Module 'HeliumLogger' (2 sources)
**/home/user/hello-api/.build/checkouts/HeliumLogger.git-7972212279880105712/Sources/HeliumLogger/HeliumLogger.swift:116:39: error: use of undeclared type 'RegularExpression'
    typealias RegularExpressionType = RegularExpression**
                                      ^~~~~~~~~~~~~~~~~
**/home/user/hello-api/.build/checkouts/HeliumLogger.git-7972212279880105712/Sources/HeliumLogger/HeliumLogger.swift:121:24: error: could not infer type for 'tokenRegex'
    private static var tokenRegex: RegularExpressionType? = {**
                       ^
**/home/user/hello-api/.build/checkouts/HeliumLogger.git-7972212279880105712/Sources/HeliumLogger/HeliumLogger.swift:116:39: error: use of undeclared type 'RegularExpression'
    typealias RegularExpressionType = RegularExpression**
                                      ^~~~~~~~~~~~~~~~~

**Comment by shmuelk** [comment]
You were building Kitura against Swift 3.1, not Swift 3.0.2.
