### ISSUE TITLE
fail to staging swift application with latest 1.7.0 version 

### ISSUE THREAD

**Issue by cdlliuy** [IBM-Swift/HeliumLogger#47]
When running with the swift application https://github.com/IBM-Bluemix/Kitura-Starter,  it is fine with HeliumLogger 1.6.x version.

But if I use majorVersion directly, 
  .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git"  , majorVersion: 1), then staging failed.

       Cloning https://github.com/IBM-Swift/HeliumLogger.git
       HEAD is now at 9b310ce IBM-Swift/Kitura#1047 Swift 3.1 changes
swift-build: error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/LoggerAPI.git)
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
       Resolved version: 1.7.0
Successfully destroyed container

**Comment by na-gupta** [comment]
The problem is that Kitura is tagged with a major(1) and minor(6) version and HeliumLogger is tagged with just the major version. We need to be consistent in how we tag Kitura and related repos to avoid dependency graph problems (preferably by including the minor version).

**Comment by carlbrown** [comment]
The version of `HeliumLogger` and the version of `Kitura` need to match.

So if you change `HeliumLogger` to:
```
.Package(url: "https://github.com/IBM-Swift/HeliumLogger.git" , majorVersion: 1)
```

Then you need to change Kitura to:
```
.Package(url: "https://github.com/IBM-Swift/Kitura.git" , majorVersion: 1)
```
as well.

**Comment by helenmasters** [comment]
@cdlliuy can this issue be closed off now?

**Comment by ianpartridge** [comment]
No response so closing, please reopen if you still need help.
