### ISSUE TITLE
Support logging to syslog and text files

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/HeliumLogger#49]

**Comment by shmuelk** [comment]
If you want more sophisticated logging than that which is provided by HeliumLogger, I'd suggest you look at https://github.com/SwiftyBeaver/SwiftyBeaver-Kitura.

**Comment by NocturnalSolutions** [comment]
HeliumLogger lets you log to implementations of TextOutputStream. See [HeliumStreamLogger.swift](https://github.com/IBM-Swift/HeliumLogger/blob/master/Sources/HeliumLogger/HeliumStreamLogger.swift).

Here's some code I threw together to log to stderr (thanks to https://deepswift.com/core/standard-io/ ). You can probably see where you can adapt it to write to a text file instead.

```swift
struct StandardError: TextOutputStream {
    func write(_ text: String) {
        guard let data = text.data(using: String.Encoding.utf8) else {
            return
        }
        FileHandle.standardError.write(data)
    }
}

let se = StandardError()
HeliumStreamLogger.use(outputStream: se)
```

Then log as normal.

**Comment by gmosx** [comment]
Nice tips guys, thank you.

**Comment by shmuelk** [comment]
In general logging to files is more involved than just writing to a file. Generally to be useful one needs log rotation (one hopes one's server will run for a really long time which makes for very large log files...) and some minimal management to insure that the file system doesn't fill up with log files......

**Comment by NocturnalSolutions** [comment]
…but sometimes one just needs to see what's going on in one's code and a debugger isn't a good fit for certain cases. And any server OS worth being called as much will already ship with log rotation tools if one really needs to log so much stuff in production that filling up a disk is a worry.

Are you really a contributor to this project? You seem to be very interested in talking us down from using it in favor of a commercial alternative. Hmm.

**Comment by shmuelk** [comment]
I am a contributor to Kitura.

The goal of HeliumLogger was to be a very simple and lightweight logger. The idea of the LoggerAPI in Kitura was to enable the plugging in of all sorts of loggers, not just those supplied by Kitura.

Even open source servers that log to disk, have built in facilities to switch log files when the log file is over a certain size.

I agree that sometimes simplistic logging to a file is useful.

**Comment by helenmasters** [comment]
@gmosx I've put the code example which is referenced above into the API reference for HeliumStreamLogger here ->

http://ibm-swift.github.io/HeliumLogger/Classes/HeliumStreamLogger.html#/s:12HeliumLogger0a6StreamB0C3usey0B3API0B11MessageTypeO_x06outputC0tFZ

If this resolves your issue please can you close it. If it doesn't and you'd like additional documentation please let me know what and where and I'll address it.
