### ISSUE TITLE
How to log to file?#Question

### ISSUE THREAD

**Issue by zzyyzz1992** [IBM-Swift/HeliumLogger#6]
How to log to local file path?
Please forgive me that this maybe a dumb question.
Thanks:)

**Comment by ianpartridge** [comment]
Currently HeliumLogger only logs to stdout.  You can redirect stdout to a file using your shell.

**Comment by zzyyzz1992** [comment]
Thanks @ianpartridge , case close 👍

**Comment by rfdickerson** [comment]
Yeah, logging to stdout is very convenient for making them show up in the Cloud Foundry logs.
